
service: currency

plugins:
  - serverless-dotenv-plugin

custom:
  bucket: nomeyho-currency-${self:provider.stage}

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  apiKeys:
    - currencyApiKey-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action: '*'
      Resource: 'arn:aws:s3:::${self:custom.bucket}/*'
    - Effect: Allow
      Action:
        - 'ses:SendEmail'
        - 'ses:SendRawEmail'
      Resource: '*'

# Lambda
functions:
  refresh:
    handler: src/handler.refresh
    memorySize: 256
    events:
      - schedule:
          rate: cron(4 0 * * ? *)
      - http:
          path: /currency/refresh
          method: POST
          cors: true
          private: true
    environment:
      FIXER_API_KEY: ${env:FIXER_API_KEY}
      BUCKET_NAME: ${self:custom.bucket}
      REGION: ${self:provider.region}
      EMAIL: ${env:EMAIL}

# S3
resources:
  Resources:
    currencyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
    currencyBucketPolicy:
      Type: AWS::S3::BucketPolicy
      DependsOn: currencyBucket
      Properties:
        Bucket: 
          Ref: currencyBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Principal: '*'
                Resource: 'arn:aws:s3:::${self:custom.bucket}/*'
          
